spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://provisioning-db:5432/provisioning}
  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/univerliga}

app:
  keycloak:
    base-url: ${KEYCLOAK_URL:http://keycloak:8080}
